/* THE GATE PASS SLIP — what security checks as the lorry leaves.
 *
 * The factory's slip is a pre-printed book: a serial number at the top right,
 * the party and city, the transporter, and one row per article/size with the
 * carton count, the MRP, the standard pack and the pairs. It is signed by the
 * dispatch supervisor and by security.
 *
 * It is built from the SAME packing list that goes with the lorry, so the two
 * cannot disagree — the pairs on the gate pass are the pairs that were packed,
 * and the carton totals are the ones the packer counted.
 *
 * TWO NUMBERS ARE NEVER INVENTED HERE:
 *
 *   THE SERIAL NUMBER is printed in the book, not by us. The factory writes
 *   15945 from the pad in front of them; a number generated by the app would
 *   be a second, competing series. It is typed in, and prints blank until it
 *   is.
 *
 *   THE MRP AND STANDARD PACK come from the article master, per SIZE, and are
 *   left BLANK where there is no figure on record. A blank tells the gate to
 *   check; a zero tells it the shoes are free.
 *
 * Pure: no database, no clock.
 */

/* Number(null) is 0, and 0 is a finite number — so a missing MRP came back as
   a price of zero, which on a gate pass says the shoes are free. Nothing
   without a value is ever turned into one. */
const num = v => {
  if(v == null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};
const int = v => { const n = Number(v); return Number.isFinite(n) ? Math.round(n) : 0; };
const text = v => String(v == null ? "" : v).trim();

/* One row per SIZE, in the order the packing list prints them, because the
   gate checks the two side by side. Sizes that share a carton stay separate
   rows — security counts pairs by size — while the carton count sits against
   the group that was actually boxed. */
export function gatePassRows(built, opts = {}){
  const mrpFor = opts.mrpFor || (() => null);
  const packFor = opts.packFor || (() => null);
  const rows = [];
  let sno = 0;
  for(const line of (built && built.lines) || []){
    for(const group of line.groups || []){
      const sizes = group.sizes || [];
      sizes.forEach((s, i) => {
        sno += 1;
        rows.push({
          sno,
          article: line.article,
          size: s.size,
          colour: line.colour,
          closure: line.closure,
          /* The carton figure belongs to the GROUP, so it is written once
             against its first size and left blank on the rest — repeating it
             would treble the count at the gate. */
          cartons: i === 0 ? group.cartons : null,
          carton_numbers: i === 0 && group.cn_from
            ? (group.cn_from === group.cn_to ? `${group.cn_from}` : `${group.cn_from}-${group.cn_to}`)
            : null,
          mixed: sizes.length > 1,
          mrp: num(mrpFor(s.size, line)),
          std_pack: num(packFor(s.size, line)),
          pairs: int(s.pairs),
        });
      });
    }
  }
  return rows;
}

export function buildGatePass(input = {}){
  const built = input.packing_list || { lines: [], total_pairs: 0, total_cartons: 0 };
  const rows = gatePassRows(built, input);
  const problems = [];

  const total_pairs = rows.reduce((a, r) => a + r.pairs, 0);
  const total_cartons = rows.reduce((a, r) => a + (r.cartons || 0), 0);

  /* The gate pass and the packing list are the same shipment. If they differ,
     something was edited after the sheet was made and the lorry would leave
     with two documents that disagree. */
  if(built.total_pairs != null && total_pairs !== built.total_pairs)
    problems.push(`The gate pass adds up to ${total_pairs} pairs and the packing list says ${built.total_pairs}`);
  if(built.total_cartons != null && total_cartons !== built.total_cartons)
    problems.push(`The gate pass adds up to ${total_cartons} cartons and the packing list says ${built.total_cartons}`);

  const missingMrp = rows.filter(r => r.mrp == null).length;
  const missingPack = rows.filter(r => r.std_pack == null).length;

  return {
    /* Typed from the pre-printed book. Blank until it is. */
    serial_no: text(input.serial_no),
    party: text(input.party || built.customer),
    city: text(input.city),
    transporter: text(input.transporter),
    date: input.date || built.date || null,
    order_no: text(input.order_no || built.order_no),
    order_qty: input.order_qty == null ? null : int(input.order_qty),
    rows, total_pairs, total_cartons,
    /* Named rather than silently blank, so the person at the gate knows the
       figure is missing from the master and not from the shipment. */
    missing_mrp: missingMrp,
    missing_pack: missingPack,
    problems,
    ok: problems.length === 0,
  };
}
